# Generated by Django 2.0.2 on 2018-04-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_keste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='god',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='izdanie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='literature_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='stranica',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='literature',
            name='typee',
            field=models.CharField(blank=True, choices=[('Н', 'Негізгі'), ('Қ', 'Қосымша')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
