# Generated by Django 2.0.2 on 2018-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180421_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takyryp',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
