# Generated by Django 2.0.2 on 2018-04-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_teacher_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user_name',
            new_name='username',
        ),
    ]
