# Generated by Django 2.0.2 on 2018-04-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20180425_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='user',
        ),
    ]
