# Generated by Django 2.0.2 on 2018-04-25 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0023_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literature',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='takyryp',
            name='subject',
        ),
        migrations.AddField(
            model_name='lit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='literature',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='literature',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Literature'),
        ),
        migrations.AddField(
            model_name='subject',
            name='takyryp',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Takyryp'),
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='takyryp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Subject'),
        ),
        migrations.AddField(
            model_name='zert_jumys',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
